# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yedarm Seong
title: Master Student, Seoul National University
email: mybirth0407@gmail.com
website: github.com/mybirth0407

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: mybirth0407
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mybirth0407
linkedin_username: yedarm-seong
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# # Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# # - title: another link
# #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
# #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Yedarm Seong and a master stuent in Seoul Natiaonal University. My research interests focus on <mark>Mathematics for Machine Learning</mark>, <mark>Reinforcement Learning</mark>, <mark>Explainable AI</mark>. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul Nataional University
        caption: 2021 - 2023 (expected)
        sub_title: Master, Computational Science
        quote: >
          To be updated.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

      - layout: left
        title: Hanyang University
        caption: 2013 - 2018
        sub_title: Bachelor, Computer Science
        quote: >
          Project, The Theorical Mass Spectra Prediction using Deep Learning.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Numerical Computing and Image Analysis Lab.
        sub_title: Research Assistant
        caption: March 2021 - Present
        quote: >
          Computer Vision; Computational Science; Reinforcement Learning
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Institute for the Psychological Sciences
        sub_title: Research Assistant
        caption: July 2020 - December 2020
        quote: >
          Model-based fMRI; Machine Learning
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: BioIntelligence Lab.
        sub_title: Research Assistant
        caption: July 2018 - March 2019
        quote: >
          Computer Vision; Natual Language Processing
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: System Neuroscience Lab.
        sub_title: Research Assistant
        caption: April 2018 - May 2019
        quote: >
          Computational Neuroscience; Reinforcement Learning
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Signal Processing Lab.
        sub_title: Undergraduate Research Assistant
        caption: July 2017 - February 2018
        quote: >
          Deep Learning
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Working Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ZOYI Corporation
        link: https://zoyi.co
        link_text: zoyi.co
        sub_title: Data Analyst
        caption: July 2019 - May 2020
        quote: >
          Natural Language Processing; Funnel Data Analysis
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Surromind Robotics
        link: http://surromind.ai/
        link_text: surromind.ai
        sub_title: Assistant Researcher
        caption: October 2018 - March 2019
        quote: >
          Computer Vision; Natual Language Processing; Deep Learning Model Serving
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: ESTsoft
        link: https://www.estsoft.ai/
        link_text: estsoft.ai
        sub_title: Assistant Developer
        caption: March 2016 - February 2017
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Teaching/Mentoring Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Upstage AI
        link: https://boostcamp.connect.or.kr/
        link_text: boostcamp.connect.or.kr
        sub_title: Mentor
        caption: December 2020 - Present
        quote: >
          Mentoring; Competition; Deep Learning Basics;
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
